import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/utils/header/page";
import { inter } from "./fonts/fonts";
import ClientProvider from "@/components/provider/ClientProvider";
import HeaderWrapper from "@/utils/header/HeaderWrapper";
import Upload from "@/components/posts/Upload";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Fakebook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-slate-100`}>
        <div className="flex w-full items-center sticky top-0 z-10">
          <ClientProvider><HeaderWrapper /></ClientProvider>
        </div>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}