import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/utils/header/page";
import { inter } from "./fonts/fonts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
      
        className={`${inter.className} antialiased bg-slate-100`}
        
      >
        <div className="flex w-full items-center sticky top-0 z-50">
        <Header></Header>
        </div>
       
        {children}
      </body>
    </html>
  );
}
